---
Name: iqbasepages
---
Page:
  extensions:
    - IQnection\BasePage\PageExtension
PageController:
  extensions:
    - IQnection\BasePage\PageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iqnection-pages/basepages:css/leftandmainadditions.css
SilverStripe\Code\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: IQnection\MemberLoginForm\MemberLoginFormExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Iqnection\BasePage\SiteConfigExtension
---