---
Name: iqbasepages
After:
  - 'framework/*'
  - 'cms/*'
---
Page:
  extensions:
    - IqBasePageExtension
PageController:
  extensions:
    - IqBasePageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iq-basepages/css/cms/leftandmainadditions.css
SilverStripe\Code\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: MemberLoginFormExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IqBasePagesSiteConfigExtension
---