---
Name: iqbasepages
--- 
Page:
  extensions:
    - IQBase_Page
Page_Controller:
  extensions:
    - IQBase_Page_Controller
LeftAndMain:
  extra_requirements_css:
    - iq-basepages/css/cms/leftandmainadditions.css
Injector:
  MemberLoginForm:
    class: MemberLoginForm_Extension
SiteConfig:
  extensions:
    - BasePages_SiteConfig
Director:
  rules:
    'cachetemplate//$Action/': 'Page_Controller'