---
Name: iqbase
---
Page:
  extensions:
    - IQnection\Base\PageExtension
PageController:
  extensions:
    - IQnection\Base\PageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iqnection-pages/basepages:client/css/cms/leftandmainadditions.css
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Iqnection\Base\SiteConfigExtension

